language: node_js
node_js:
  - "4.0"
install:
  - npm i -g polymer-cli
  - npm install -g firebase-tools  
script:
  - echo "construyendo" && polymer build 
after_success:  
  - firebase deploy --token $FIREBASE_TOKEN
