language: node_js
node_js:
  - "4.0"
script:
  - echo "Desplegando !!"
install:
  - npm i -g polymer-cli
  - npm install -g firebase-tools
after_success:
  - polymer build
  - firebase deploy --token $FIREBASE_TOKEN
